// Verbatim Shopify Buy Button embed code for each product. Do not modify —
// these are generated by Shopify and pasted as-is. The ShopifyBuyButton
// component injects each block after the shared SDK is ready.

export const EMBED_PRODUCT_1 = `<div id='product-component-1787028133438'></div>
<script type="text/javascript">
/*<![CDATA[*/
(function () {
  var scriptURL = 'https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js';
  if (window.ShopifyBuy) {
    if (window.ShopifyBuy.UI) {
      ShopifyBuyInit();
    } else {
      loadScript();
    }
  } else {
    loadScript();
  }
  function loadScript() {
    var script = document.createElement('script');
    script.async = true;
    script.src = scriptURL;
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(script);
    script.onload = ShopifyBuyInit;
  }
  function ShopifyBuyInit() {
    var client = ShopifyBuy.buildClient({
      domain: 'i1qu01-q1.myshopify.com',
      storefrontAccessToken: 'd46a6f67c2416ddad6db62cabaf76541',
    });
    ShopifyBuy.UI.onReady(client).then(function (ui) {
      ui.createComponent('product', {
        id: '9896483061995',
        node: document.getElementById('product-component-1787028133438'),
        moneyFormat: '%24%7B%7Bamount%7D%7D',
        options: {
  "product": {
    "contents": {
      "title": true,
      "description": false
    },
    "styles": {
      "product": {
        "max-width": "280px",
        "margin-left": "auto",
        "margin-right": "auto",
        "@media (min-width: 601px)": {
          "max-width": "280px",
          "margin-left": "auto",
          "margin-right": "auto",
          "margin-bottom": "0px"
        }
      },
      "button": {
        ":hover": {
          "background-color": "#9e7d17"
        },
        "background-color": "#af8b19",
        ":focus": {
          "background-color": "#9e7d17"
        }
      }
    },
    "text": {
      "button": "Add to Cart"
    }
  },
  "productSet": {
    "styles": {
      "products": {
        "@media (min-width: 601px)": {
          "margin-left": "-20px"
        }
      }
    }
  },
  "modalProduct": {
    "contents": {
      "img": false,
      "imgWithCarousel": true,
      "button": false,
      "buttonWithQuantity": true
    },
    "styles": {
      "product": {
        "@media (min-width: 601px)": {
          "max-width": "100%",
          "margin-left": "0px",
          "margin-bottom": "0px"
        }
      },
      "button": {
        ":hover": {
          "background-color": "#9e7d17"
        },
        "background-color": "#af8b19",
        ":focus": {
          "background-color": "#9e7d17"
        }
      }
    },
    "text": {
      "button": "Add to Cart"
    }
  },
  "option": {},
  "cart": {
    "styles": {
      "button": {
        ":hover": {
          "background-color": "#9e7d17"
        },
        "background-color": "#af8b19",
        ":focus": {
          "background-color": "#9e7d17"
        }
      }
    },
    "text": {
      "total": "Subtotal",
      "button": "Checkout"
    }
  },
  "toggle": {
    "styles": {
      "toggle": {
        "background-color": "#af8b19",
        ":hover": {
          "background-color": "#9e7d17"
        },
        ":focus": {
          "background-color": "#9e7d17"
        }
      }
    }
  }
},
      });
    });
  }
})();
/*]]>*/
</script>`;

export const EMBED_PRODUCT_3 = `<div id='product-component-1787433042014'></div>
<script type="text/javascript">
/*<![CDATA[*/
(function () {
  var scriptURL = 'https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js';
  if (window.ShopifyBuy) {
    if (window.ShopifyBuy.UI) {
      ShopifyBuyInit();
    } else {
      loadScript();
    }
  } else {
    loadScript();
  }
  function loadScript() {
    var script = document.createElement('script');
    script.async = true;
    script.src = scriptURL;
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(script);
    script.onload = ShopifyBuyInit;
  }
  function ShopifyBuyInit() {
    var client = ShopifyBuy.buildClient({
      domain: 'i1qu01-q1.myshopify.com',
      storefrontAccessToken: 'd46a6f67c2416ddad6db62cabaf76541',
    });
    ShopifyBuy.UI.onReady(client).then(function (ui) {
      ui.createComponent('product', {
        id: '9905052221675',
        node: document.getElementById('product-component-1787433042014'),
        moneyFormat: '%24%7B%7Bamount%7D%7D',
        options: {
  "product": {
    "styles": {
      "product": {
        "@media (min-width: 601px)": {
          "max-width": "calc(25% - 20px)",
          "margin-left": "20px",
          "margin-bottom": "50px"
        }
      },
      "button": {
        ":hover": {
          "background-color": "#9e7d17"
        },
        "background-color": "#af8b19",
        ":focus": {
          "background-color": "#9e7d17"
        }
      }
    },
    "text": {
      "button": "Add to cart"
    }
  },
  "productSet": {
    "styles": {
      "products": {
        "@media (min-width: 601px)": {
          "margin-left": "-20px"
        }
      }
    }
  },
  "modalProduct": {
    "contents": {
      "img": false,
      "imgWithCarousel": true,
      "button": false,
      "buttonWithQuantity": true
    },
    "styles": {
      "product": {
        "@media (min-width: 601px)": {
          "max-width": "100%",
          "margin-left": "0px",
          "margin-bottom": "0px"
        }
      },
      "button": {
        ":hover": {
          "background-color": "#9e7d17"
        },
        "background-color": "#af8b19",
        ":focus": {
          "background-color": "#9e7d17"
        }
      }
    },
    "text": {
      "button": "Add to cart"
    }
  },
  "option": {},
  "cart": {
    "styles": {
      "button": {
        ":hover": {
          "background-color": "#9e7d17"
        },
        "background-color": "#af8b19",
        ":focus": {
          "background-color": "#9e7d17"
        }
      }
    },
    "text": {
      "total": "Subtotal",
      "button": "Checkout"
    }
  },
  "toggle": {
    "styles": {
      "toggle": {
        "background-color": "#af8b19",
        ":hover": {
          "background-color": "#9e7d17"
        },
        ":focus": {
          "background-color": "#9e7d17"
        }
      }
    }
  }
},
      });
    });
  }
})();
/*]]>*/
</script>`;

export const EMBED_PRODUCT_4 = `<div id='product-component-1787433579034'></div>
<script type="text/javascript">
/*<![CDATA[*/
(function () {
  var scriptURL = 'https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js';
  if (window.ShopifyBuy) {
    if (window.ShopifyBuy.UI) {
      ShopifyBuyInit();
    } else {
      loadScript();
    }
  } else {
    loadScript();
  }
  function loadScript() {
    var script = document.createElement('script');
    script.async = true;
    script.src = scriptURL;
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(script);
    script.onload = ShopifyBuyInit;
  }
  function ShopifyBuyInit() {
    var client = ShopifyBuy.buildClient({
      domain: 'i1qu01-q1.myshopify.com',
      storefrontAccessToken: 'd46a6f67c2416ddad6db62cabaf76541',
    });
    ShopifyBuy.UI.onReady(client).then(function (ui) {
      ui.createComponent('product', {
        id: '9904687284459',
        node: document.getElementById('product-component-1787433579034'),
        moneyFormat: '%24%7B%7Bamount%7D%7D',
        options: {
  "product": {
    "styles": {
      "product": {
        "@media (min-width: 601px)": {
          "max-width": "calc(25% - 20px)",
          "margin-left": "20px",
          "margin-bottom": "50px"
        }
      },
      "button": {
        ":hover": {
          "background-color": "#9e7d17"
        },
        "background-color": "#af8b19",
        ":focus": {
          "background-color": "#9e7d17"
        }
      }
    },
    "text": {
      "button": "Add to cart"
    }
  },
  "productSet": {
    "styles": {
      "products": {
        "@media (min-width: 601px)": {
          "margin-left": "-20px"
        }
      }
    }
  },
  "modalProduct": {
    "contents": {
      "img": false,
      "imgWithCarousel": true,
      "button": false,
      "buttonWithQuantity": true
    },
    "styles": {
      "product": {
        "@media (min-width: 601px)": {
          "max-width": "100%",
          "margin-left": "0px",
          "margin-bottom": "0px"
        }
      },
      "button": {
        ":hover": {
          "background-color": "#9e7d17"
        },
        "background-color": "#af8b19",
        ":focus": {
          "background-color": "#9e7d17"
        }
      }
    },
    "text": {
      "button": "Add to cart"
    }
  },
  "option": {},
  "cart": {
    "styles": {
      "button": {
        ":hover": {
          "background-color": "#9e7d17"
        },
        "background-color": "#af8b19",
        ":focus": {
          "background-color": "#9e7d17"
        }
      }
    },
    "text": {
      "total": "Subtotal",
      "button": "Checkout"
    }
  },
  "toggle": {
    "styles": {
      "toggle": {
        "background-color": "#af8b19",
        ":hover": {
          "background-color": "#9e7d17"
        },
        ":focus": {
          "background-color": "#9e7d17"
        }
      }
    }
  }
},
      });
    });
  }
})();
/*]]>*/
</script>`;

export const EMBED_PRODUCT_5 = `<div id='product-component-1787610247128'></div>
<script type="text/javascript">
/*<![CDATA[*/
(function () {
  var scriptURL = 'https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js';
  if (window.ShopifyBuy) {
    if (window.ShopifyBuy.UI) {
      ShopifyBuyInit();
    } else {
      loadScript();
    }
  } else {
    loadScript();
  }
  function loadScript() {
    var script = document.createElement('script');
    script.async = true;
    script.src = scriptURL;
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(script);
    script.onload = ShopifyBuyInit;
  }
  function ShopifyBuyInit() {
    var client = ShopifyBuy.buildClient({
      domain: 'i1qu01-q1.myshopify.com',
      storefrontAccessToken: 'd46a6f67c2416ddad6db62cabaf76541',
    });
    ShopifyBuy.UI.onReady(client).then(function (ui) {
      ui.createComponent('product', {
        id: '9908938997995',
        node: document.getElementById('product-component-1787610247128'),
        moneyFormat: '%24%7B%7Bamount%7D%7D',
        options: {
  "product": {
    "styles": {
      "product": {
        "@media (min-width: 601px)": {
          "max-width": "calc(25% - 20px)",
          "margin-left": "20px",
          "margin-bottom": "50px"
        }
      },
      "button": {
        ":hover": {
          "background-color": "#9e7d17"
        },
        "background-color": "#af8b19",
        ":focus": {
          "background-color": "#9e7d17"
        }
      }
    },
    "text": {
      "button": "Add to cart"
    }
  },
  "productSet": {
    "styles": {
      "products": {
        "@media (min-width: 601px)": {
          "margin-left": "-20px"
        }
      }
    }
  },
  "modalProduct": {
    "contents": {
      "img": false,
      "imgWithCarousel": true,
      "button": false,
      "buttonWithQuantity": true
    },
    "styles": {
      "product": {
        "@media (min-width: 601px)": {
          "max-width": "100%",
          "margin-left": "0px",
          "margin-bottom": "0px"
        }
      },
      "button": {
        ":hover": {
          "background-color": "#9e7d17"
        },
        "background-color": "#af8b19",
        ":focus": {
          "background-color": "#9e7d17"
        }
      }
    },
    "text": {
      "button": "Add to cart"
    }
  },
  "option": {},
  "cart": {
    "styles": {
      "button": {
        ":hover": {
          "background-color": "#9e7d17"
        },
        "background-color": "#af8b19",
        ":focus": {
          "background-color": "#9e7d17"
        }
      }
    },
    "text": {
      "total": "Subtotal",
      "button": "Checkout"
    }
  },
  "toggle": {
    "styles": {
      "toggle": {
        "background-color": "#af8b19",
        ":hover": {
          "background-color": "#9e7d17"
        },
        ":focus": {
          "background-color": "#9e7d17"
        }
      }
    }
  }
},
      });
    });
  }
})();
/*]]>*/
</script>`;

export const EMBED_PRODUCT_2 = `<div id='product-component-1787028184356'></div>
<script type="text/javascript">
/*<![CDATA[*/
(function () {
  var scriptURL = 'https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js';
  if (window.ShopifyBuy) {
    if (window.ShopifyBuy.UI) {
      ShopifyBuyInit();
    } else {
      loadScript();
    }
  } else {
    loadScript();
  }
  function loadScript() {
    var script = document.createElement('script');
    script.async = true;
    script.src = scriptURL;
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(script);
    script.onload = ShopifyBuyInit;
  }
  function ShopifyBuyInit() {
    var client = ShopifyBuy.buildClient({
      domain: 'i1qu01-q1.myshopify.com',
      storefrontAccessToken: 'd46a6f67c2416ddad6db62cabaf76541',
    });
    ShopifyBuy.UI.onReady(client).then(function (ui) {
      ui.createComponent('product', {
        id: '9896048787691',
        node: document.getElementById('product-component-1787028184356'),
        moneyFormat: '%24%7B%7Bamount%7D%7D',
        options: {
  "product": {
    "contents": {
      "title": true,
      "description": false
    },
    "styles": {
      "product": {
        "max-width": "280px",
        "margin-left": "auto",
        "margin-right": "auto",
        "@media (min-width: 601px)": {
          "max-width": "280px",
          "margin-left": "auto",
          "margin-right": "auto",
          "margin-bottom": "0px"
        }
      },
      "button": {
        ":hover": {
          "background-color": "#9e7d17"
        },
        "background-color": "#af8b19",
        ":focus": {
          "background-color": "#9e7d17"
        }
      }
    },
    "text": {
      "button": "Add to Cart"
    }
  },
  "productSet": {
    "styles": {
      "products": {
        "@media (min-width: 601px)": {
          "margin-left": "-20px"
        }
      }
    }
  },
  "modalProduct": {
    "contents": {
      "img": false,
      "imgWithCarousel": true,
      "button": false,
      "buttonWithQuantity": true
    },
    "styles": {
      "product": {
        "@media (min-width: 601px)": {
          "max-width": "100%",
          "margin-left": "0px",
          "margin-bottom": "0px"
        }
      },
      "button": {
        ":hover": {
          "background-color": "#9e7d17"
        },
        "background-color": "#af8b19",
        ":focus": {
          "background-color": "#9e7d17"
        }
      }
    },
    "text": {
      "button": "Add to Cart"
    }
  },
  "option": {},
  "cart": {
    "styles": {
      "button": {
        ":hover": {
          "background-color": "#9e7d17"
        },
        "background-color": "#af8b19",
        ":focus": {
          "background-color": "#9e7d17"
        }
      }
    },
    "text": {
      "total": "Subtotal",
      "button": "Checkout"
    }
  },
  "toggle": {
    "styles": {
      "toggle": {
        "background-color": "#af8b19",
        ":hover": {
          "background-color": "#9e7d17"
        },
        ":focus": {
          "background-color": "#9e7d17"
        }
      }
    }
  }
},
      });
    });
  }
})();
/*]]>*/
</script>`;